# Generated by Django 2.2.4 on 2019-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='descripcion',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
